version: "3.9"
services:
  game-postgres:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "dbAdmin"
      POSTGRES_DB: "game"
    ports:
      - '5407:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
